# 2023-10-11 23:00
name: act-Release

on:
  workflow_dispatch:
#  push:
#    tags:
#      - "v*"

jobs:

  build-artifacts:
    strategy:
      fail-fast: false
      matrix:
        build: [ x64, x86 , ARM64 ]
        include:
          - { build: x64,    arch: amd64,       triplet: x64-windows-static-rel, }
          - { build: x86,    arch: amd64_x86,   triplet: x86-windows-static-rel, }
          - { build: ARM64,  arch: amd64_arm64, triplet: arm64-windows-static-rel, }

    env:
      BUILD_TYPE: Release
      X_VCPKG_NUGET_ID_PREFIX: 'farcolorer'
      VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'

    runs-on: windows-2019
    steps:
      - name: Checkout source
        uses: deep-soft/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      #- name: Get version
      #  id: get_version
      #  uses: deep-soft/get-version-action@v4

      - name: Get version
        id: get_version
        shell: bash
        run: |
          get_version=$(cat version4far.txt)
          echo "version=$get_version"
          echo "version=$get_version" >>$GITHUB_OUTPUT

      - name: Add C++ build tools to PATH
        uses: deep-soft/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Setup cache
        uses: deep-soft/cache@v3
        with:
          path: ${{ github.workspace }}
          key: cache-${{ matrix.arch }}
          restore-keys: |
            cache-${{ matrix.arch }}

      - name: Install vcpkg
        run: |
          cd external\colorer\external\vcpkg
          .\bootstrap-vcpkg.bat

      - name: Setup NuGet Credentials for vpckg cache
        shell: bash
        run: >
          `$VCPKG_INSTALLATION_ROOT/vcpkg fetch nuget | tail -n 1`
          sources add
          -source "https://nuget.pkg.github.com/colorer/index.json"
          -storepasswordincleartext
          -name "GitHub"
          -username "${{ secrets.PACKAGES_GITHUB_USER }}"
          -password "${{ secrets.PACKAGES_GITHUB_TOKEN }}"

      - name: Create Build folder
        run: cmake -E make_directory build

      - name: Configure CMake
        shell: bash
        working-directory: build
        run: >
          cmake $GITHUB_WORKSPACE -G "Ninja"
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE
          -DCOLORER_BUILD_ARCH=${{ matrix.build }}
          -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/external/colorer/external/vcpkg/scripts/buildsystems/vcpkg.cmake
          -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }}
          -DVCPKG_OVERLAY_PORTS=$GITHUB_WORKSPACE/external/colorer/external/vcpkg-ports
          -DVCPKG_OVERLAY_TRIPLETS=$GITHUB_WORKSPACE/external/colorer/external/vcpkg-triplets
          -DVCPKG_FEATURE_FLAGS=manifests,versions
          -DCMAKE_INSTALL_PREFIX=./install/FarColorer

      - name: Build
        working-directory: build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Install
        working-directory: build
        shell: bash
        run: cmake --install . --config $BUILD_TYPE

      - name: Download scheme
        working-directory: build
        shell: bash
        run: |
          echo "ls1"
          ls -la *.zip
          zipfilename="$(find . -name "colorer-base*.zip")"
          if [[ -f $zipfilename ]]; then
            rm $zipfilename
          fi
          curl -s https://api.github.com/repos/colorer/Colorer-schemes/releases/latest | grep -o "https://.*colorer-base\.allpacked.*.zip" | xargs curl -v -fsLJO
          echo "ls2"
          ls -la *.zip
          zipfilename="$(find . -name "colorer-base*.zip")"
          7z x $zipfilename -o./install/FarColorer/base
          rm $zipfilename
          echo "ls3"
          ls -la *.zip

      - name: Set the pack file name
        shell: bash
        run: |
          echo "farcolorer_name=FarColorer.${{ matrix.build }}.${{ steps.get_version.outputs.version }}.7z" >> $GITHUB_ENV
          echo "farcolorer_pdb_name=FarColorer.${{ matrix.build }}.${{ steps.get_version.outputs.version }}.pdb.7z" >> $GITHUB_ENV
          echo "farcolorer_withoutbase_name=FarColorer.${{ matrix.build }}.${{ steps.get_version.outputs.version }}.wobase.7z" >> $GITHUB_ENV

      - name: pack plugin
        working-directory: build
        shell: bash
        run: |
          7z a -m0=LZMA -mf=BCJ2 -mx9 ${{ env.farcolorer_name }} ./install/FarColorer/*
          7z a -m0=LZMA -mf=BCJ2 -mx9 ${{ env.farcolorer_withoutbase_name }} ./install/FarColorer/* -x!./install/FarColorer/base
          7z a -m0=LZMA -mf=off -mx9 ${{ env.farcolorer_pdb_name }} ./src/colorer.pdb

      - name: Upload result to cache
        uses: actions/upload-artifact@v3
        with:
          name: result
          path: ./build/*.7z
          retention-days: 1

  publish-release:
    needs: [ build-artifacts ]
    runs-on: windows-2019

    steps:
      - name: Checkout source
        uses: deep-soft/checkout@v4

      #- name: Get version
      #  id: get_version
      #  uses: deep-soft/get-version-action@v3

      - name: Get version
        id: get_version
        shell: bash
        run: |
          get_version=$(cat version4far.txt)
          echo "version=$get_version"
          echo "version=$get_version" >>$GITHUB_OUTPUT

      - name: Download result
        uses: deep-soft/download-artifact@v3
        with:
          name: result

      - name: Create release
        shell: bash
        run: gh release create ${{ steps.get_version.outputs.version }} -t "FarColorer ${{ steps.get_version.outputs.version }}" -n "New version" ./*.7z
        env:
          GITHUB_TOKEN: ${{github.token}}
