name: Build

on:
  workflow_dispatch:
#  push:
#    branches:
#      - master
#    paths-ignore:
#      - 'version4far.txt'
#      - 'README.md'
#  pull_request:
#    branches:
#      - master

env:
  BUILD_TYPE: Release
  X_VCPKG_NUGET_ID_PREFIX: 'farcolorer'
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [ x64, x86 , ARM64 ]
        include:
          - { build: x64,    arch: amd64,       triplet: x64-windows-static-rel, }
          - { build: x86,    arch: amd64_x86,   triplet: x86-windows-static-rel, }
          - { build: ARM64,  arch: amd64_arm64, triplet: arm64-windows-static-rel, }

    runs-on: windows-2022

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install vcpkg
        run: |
          cd external\colorer\external\vcpkg
          .\bootstrap-vcpkg.bat

      - name: Add C++ build tools to PATH
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Setup NuGet Credentials for cache
        shell: bash
        run: >
          `$VCPKG_INSTALLATION_ROOT/vcpkg fetch nuget | tail -n 1`
          sources add
          -source "https://nuget.pkg.github.com/colorer/index.json"
          -storepasswordincleartext
          -name "GitHub"
          -username "${{ secrets.PACKAGES_GITHUB_USER }}"
          -password "${{ secrets.PACKAGES_GITHUB_TOKEN }}"

      - name: Create Build forlder
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: >
          cmake $GITHUB_WORKSPACE -G "Ninja"
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE
          -DCOLORER_BUILD_ARCH=${{ matrix.build }}
          -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/external/colorer/external/vcpkg/scripts/buildsystems/vcpkg.cmake
          -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }}
          -DVCPKG_OVERLAY_PORTS=$GITHUB_WORKSPACE/external/colorer/external/vcpkg-ports
          -DVCPKG_OVERLAY_TRIPLETS=$GITHUB_WORKSPACE/external/colorer/external/vcpkg-triplets
          -DVCPKG_FEATURE_FLAGS=manifests,versions

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE
      
      
